# Generated by Django 4.1.1 on 2022-10-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_id_post_post_post_id_alter_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upvotepost",
            old_name="post_id",
            new_name="post",
        ),
    ]
